import type { Metadata } from "next";
import MajazApp from "@/components/majaz-app";

export const metadata: Metadata = {
  title: "سوق مجاز — أثرٌ من هنا",
  description: "سوق مجاز: قطع وإكسسوارات مستوحاة من الإرث السعودي، هدايا مختارة وتطريز شخصي.",
};

export default function HomePage() {
  return (
    <>
<main id="main">
<section className="atelier-hero"><div className="hero-words"><div className="kicker"><span className="line"></span> من إرثنا، لتفاصيلك</div><h1>أثرٌ من هنا.<br /><em>ويبقى معك.</em></h1><p>نأخذ من البشت وقاره، ومن السدو حكاياته.<br />ونصنع منها قطعًا تُحب، وهدايا لا تُنسى.</p><div className="hero-actions"><a className="btn" href="/shop">اكتشف اختيارات مجاز <span>↖</span></a><a className="text-link" href="/gifts">أبحث عن هدية <span>←</span></a></div><div className="hero-bottom"><span className="mini-symbol" aria-hidden="true">✳</span><span>جذور سعودية.<br /><b>حضور معاصر.</b></span><span className="edition" dir="ltr">THE MAJAZ EDIT<br />01 / 2026</span></div></div><div className="hero-art" aria-label="اختيارات مجاز"><div className="art-outline" aria-hidden="true"></div><a className="hero-stage" href="/product?id=shomoukh" aria-label="اكتشف حقيبة شموخ البشت"><img className="hero-product hero-slide is-active" src="/assets/shomoukh.jpg" alt="حقيبة شموخ السوداء بخيوط البشت الذهبية" fetchPriority="high" width="800" height="1000" /><img className="hero-product hero-slide" src="/assets/fareed.jpg" alt="حقيبة فريد بتطريز ذهبي" width="800" height="1000" aria-hidden="true" /><img className="hero-product hero-slide" src="/assets/gift.jpg" alt="بكج الضيافة الكامل" width="1000" height="1000" aria-hidden="true" /></a><div className="floating-detail"><img src="/assets/craft-detail.jpg" alt="لمسة من النسيج والخيط الذهبي" /><span>الجمال، عن قرب.</span></div><span className="hero-seal" aria-hidden="true">مِن هنا<br /><span>✦</span><small>إلى ذوقك</small></span><a className="art-caption" href="/product?id=shomoukh"><span>مجموعة البشت<small>حقيبة شموخ · 150 ر.س</small></span><span className="round-arrow">↖</span></a><div className="hero-motion-controls" role="group" aria-label="التحكم في صور المنتجات"><div className="hero-slide-dots"><button className="hero-dot" data-hero-slide="0" aria-label="عرض حقيبة شموخ" aria-pressed="true"></button><button className="hero-dot" data-hero-slide="1" aria-label="عرض حقيبة فريد" aria-pressed="false"></button><button className="hero-dot" data-hero-slide="2" aria-label="عرض بكج الضيافة" aria-pressed="false"></button></div></div></div></section>
<div className="benefits"><span><i>◇</i> تفاصيل مستوحاة من تراثنا</span><span><i>✦</i> اسمك يكمّل الحكاية</span><span><i>▱</i> هدايا تليق بمن تحب</span><span><i>↗</i> شحن داخل المملكة</span></div>
<section className="section discover" id="collections"><div className="section-head"><div><span className="kicker">عالم مجاز</span><h2>لكل ذوق، <em>حكاية.</em></h2></div><p>قطع ترافقك، وهدايا تعبّر عنك.<br />ابدأ من العالم الأقرب لك.</p></div><div className="world-grid"><a className="world large" href="/shop?category=bisht"><div className="world-frame"><img src="/assets/collection-bisht.jpg" alt="مجموعة حقائب البشت بخطوطها الذهبية" loading="lazy" /></div><div className="world-copy"><span className="world-number">01 /</span><small>من وقار البشت</small><h3>حضور لا يحتاج كلامًا.</h3><span>تسوّق حقائب البشت <b>↖</b></span></div></a><a className="world" href="/gifts"><div className="world-frame"><img src="/assets/gift.jpg" alt="بكج الضيافة في صندوق إهداء" loading="lazy" /></div><div className="world-copy"><span className="world-number">02 /</span><small>فنّ الإهداء</small><h3>لمن لهم مكانة.</h3><span>اكتشف الهدايا <b>↖</b></span></div></a><a className="world" href="/shop?category=beads"><div className="world-frame"><img src="/assets/beads.jpg" alt="اختيارات مجاز من المسابح" loading="lazy" /></div><div className="world-copy"><span className="world-number">03 /</span><small>تفاصيل صغيرة</small><h3>أثرٌ قريب.</h3><span>استكشف المسابح <b>↖</b></span></div></a></div></section>
<section className="section selected" id="collection"><div className="section-head"><div><span className="kicker">اختيارات مجاز</span><h2>قطع تستحق <em>الاقتناء.</em></h2></div><a className="text-link" href="/shop">تسوّق كل القطع <span>←</span></a></div><div className="filter-row" role="group" aria-label="تصفية اختيارات مجاز"><button data-home-filter="all" aria-pressed="true">كل الاختيارات</button><button data-home-filter="bisht" aria-pressed="false">حقائب البشت</button><button data-home-filter="gifts" aria-pressed="false">البكجات والهدايا</button></div><div className="product-grid" id="home-products"></div></section>
<section className="sadu-campaign" id="sadu"><img src="/assets/hero-sadu.jpg" alt="حقيبة السدو بنقوش تراثية أمام الصحراء وقت الغروب" loading="lazy" /><div className="sadu-words"><span className="kicker">الفصل الثاني · السدو</span><h2>ألوان الأرض.<br /><em>حكاية الانتماء.</em></h2><p>إيقاع النقش، ودفء اللون.<br />إرثٌ يلتقي بذوق اليوم.</p><button className="btn light" data-dialog="sadu-dialog">اقترب من المجموعة <span>↖</span></button></div><div className="campaign-meta" dir="ltr">WOVEN INTO OUR STORY — MAJAZ</div></section>
<section className="section personal-section" id="personalize"><div className="personal-stage"><div className="personal-portrait"><img src="/assets/personalize.jpg" alt="حقيبة بشت لمعاينة تطريز الاسم" loading="lazy" /><span id="name-preview">اسمك</span></div><div className="personal-caption"><span>تفصيل يحمل اسمك</span><small>معاينة تقريبية للتطريز</small></div></div><div className="personal-words"><span className="kicker">لمسة لا تشبه غيرك</span><h2>قطعة من مجاز.<br /><em>وتوقيع منك.</em></h2><p>بعض التفاصيل تجعل الهدية أقرب.<br />أضف اسمك، أو اسم من تحب، ودعها تحكي عنك.</p><label htmlFor="embroider-name">جرّب الاسم على القطعة</label><div className="name-field"><input id="embroider-name" placeholder="مثلاً: نورة" maxLength={12} autoComplete="off" /><span id="name-count" dir="ltr">0 / 12</span></div><div className="thread-options" role="group" aria-label="لون خيط المعاينة"><button data-thread="gold" aria-pressed="true"><i className="gold-dot"></i>ذهبي</button><button data-thread="silver" aria-pressed="false"><i className="silver-dot"></i>فضي</button></div><a className="btn" id="personal-link" href="/product?id=bisht-gold&personalize=1">صمّم قطعتك <span>↖</span></a><small className="personal-note">تطريز الاسم +30 ر.س · حتى 12 حرفًا</small></div></section>
<section className="gift-presentation" id="gifts" aria-labelledby="gift-title">
  <div className="gift-presentation-head">
    <div className="gift-heading"><span className="kicker">فنّ الإهداء · مجاز</span><h2 id="gift-title">هديةٌ تليق.<br /><em>وأثرٌ يبقى.</em></h2></div>
    <div className="gift-intro"><p>من وقار البشت إلى جمال التفاصيل.<br />قطعة تعبّر عن ذوقك، وتقديرك لمن تحب.</p><a className="text-link" href="/gifts">اختر هديتك <span aria-hidden="true">↖</span></a></div>
  </div>
  <figure className="gift-presentation-figure">
    <a className="gift-presentation-photo" href="/product?id=shomoukh" aria-label="اكتشف حقيبة شموخ"><img src="/assets/gift-presentation-v2.png" alt="حقيبة شموخ السوداء بتطريز البشت الذهبي داخل تصور لصندوق إهداء أخضر مفتوح" loading="lazy" width="1536" height="1024" /></a>
    <figcaption><div><span className="gift-edition" dir="ltr">THE ART OF GIVING</span><span>تفاصيل تُقدَّر. وهدية تُذكر.</span></div><a href="/product?id=shomoukh">حقيبة شموخ <span aria-hidden="true">↖</span></a></figcaption>
  </figure>
</section>
<section className="section story-section" id="story"><div className="story-title"><span className="kicker">حكايتنا</span><h2>نحمل من الأمس<br /><em>ما يليق باليوم.</em></h2><span className="story-motif" aria-hidden="true">✳</span></div><div className="story-photo"><img src="/assets/artisan.jpg" alt="مشهد من تفاصيل التطريز والحرفة" loading="lazy" /></div><div className="story-note"><span dir="ltr">ROOTED HERE. MADE FOR NOW.</span><p>مجاز مساحة يلتقي فيها التراث السعودي بالذوق المعاصر. من خطوط البشت إلى نقوش السدو، نبحث عن التفاصيل التي تحمل ذاكرة المكان، وتجد مكانها في حياتك.</p><a className="text-link" href="/shop">اكتشف أثر الحكاية <span>←</span></a></div></section>
<section className="business-section" id="corporate"><div><span className="kicker">مجاز للأعمال</span><h2>تقديرك،<br /><em>في أجمل صورة.</em></h2></div><div><p>لفريقك وشركائك وضيوفك.<br />هدايا تحمل هوية شركتك، وروح مجاز.</p><button className="btn" data-dialog="corporate-dialog">رتّب طلب هدايا لشركتك <span>↖</span></button><small>تخصيص · تغليف · بكجات مختارة</small></div><span className="business-icon" aria-hidden="true">✦</span></section>
<section className="section faq-section"><div><span className="kicker">قبل أن تختار</span><h2>كل التفاصيل، <em>واضحة.</em></h2></div><div className="faq-list"><details><summary>هل أقدر أضيف اسمًا على القطعة؟ <span>+</span></summary><p>نعم، على حقائب البشت المعروضة، بتكلفة إضافية 30 ر.س للاسم. جرّب المعاينة ثم اختر قطعتك. موضع التطريز النهائي يؤكد مع المتجر.</p></details><details><summary>كيف أختار الهدية المناسبة؟ <span>+</span></summary><p>استخدم صفحة «اختر هديتك» لتحديد نوع الهدية والميزانية، ثم استعرض الاختيارات المتاحة وأسعارها.</p></details><details><summary>ما تفاصيل الشحن والاستبدال؟ <span>+</span></summary><p>المتجر المرجعي يعرض شحنًا داخل المملكة، وشحنًا مجانيًا للطلبات فوق 300 ر.س، والاستبدال خلال 14 يومًا. تفاصيل التطبيق النهائية تؤكد مع المتجر.</p></details><details><summary>هل تتوفر هدايا للشركات؟ <span>+</span></summary><p>يمكن تجهيز موجز لطلب الشركة يتضمن الكمية والتخصيص والمناسبة. في هذه المعاينة يُحفظ الموجز محليًا لتراجعه، دون إرسال طلب فعلي.</p></details></div></section>
</main>
      <MajazApp page="home" />
    </>
  );
}
